#!/usr/bin/env ruby
# frozen_string_literal: true

require "csv"
require "date"
require "json"
require "yaml"
require "fileutils"

ROOT = File.expand_path("..", __dir__)
DATA = File.join(ROOT, "data")

def read_csv(name)
  CSV.read(File.join(DATA, name), headers: true, encoding: "bom|utf-8")
end

def truthy?(value)
  %w[true 1 yes y].include?(value.to_s.strip.downcase)
end

def month_index(date, launch_month)
  (date.year - launch_month.year) * 12 + date.month - launch_month.month
end

def month_string(launch_month, index)
  n = launch_month.year * 12 + (launch_month.month - 1) + index
  format("%04d-%02d", n / 12, n % 12 + 1)
end

meta = YAML.safe_load(File.read(File.join(DATA, "dataset.yml"), encoding: "UTF-8"))
series_defs = read_csv("series.csv").sort_by { |r| Integer(r["order"]) }
source_rows = read_csv("sources.csv")
citations = source_rows.to_h { |r| [r["id"], r] }
valid_source_ids = series_defs.map { |r| r["source_id"] }.uniq

releases = Hash.new { |h, k| h[k] = [] }
seen_exact = {}
errors = []

read_csv("releases.csv").each_with_index do |r, i|
  sid = r["source_id"].to_s.strip
  title = r["title"].to_s.strip
  date_s = r["release_date"].to_s.strip
  if sid.empty? || title.empty? || date_s.empty?
    errors << "releases.csv line #{i + 2}: source_id/release_date/title is blank"
    next
  end

  begin
    date = Date.iso8601(date_s)
  rescue Date::Error
    errors << "releases.csv line #{i + 2}: invalid date #{date_s.inspect}"
    next
  end

  key = [sid, date_s, title]
  warn "WARNING: exact duplicate: #{key.join(' | ')}" if seen_exact[key]
  seen_exact[key] = true

  releases[sid] << {
    date: date,
    title: title,
    package: r["package"].to_s.strip.downcase
  }
end

unless errors.empty?
  warn errors.join("\n")
  abort "build aborted: #{errors.size} invalid row(s)"
end

unknown = releases.keys - valid_source_ids
abort "unknown source_id(s) in releases.csv: #{unknown.join(', ')}" unless unknown.empty?

series = {}
order = []

series_defs.each do |d|
  id = d["id"].to_s
  sid = d["source_id"].to_s
  launch = Date.strptime("#{d['launch_month']}-01", "%Y-%m-%d")
  package_filter = d["package_filter"].to_s.strip
  rows = releases.fetch(sid, [])
  rows = rows.select { |r| truthy?(r[:package]) } if package_filter == "true"

  indexed = rows.map do |r|
    idx = month_index(r[:date], launch)
    abort "#{id}: #{r[:title]} has release before launch (#{r[:date]})" if idx.negative?
    [idx, r]
  end

  max_idx = indexed.map(&:first).max || 0
  counts = Array.new(max_idx + 1, 0)
  indexed.each { |idx, _| counts[idx] += 1 }
  months = (0..max_idx).map { |idx| month_string(launch, idx) }

  citation = citations.fetch(id)
  raw_rows = Integer(citation["raw_rows"].to_s.empty? ? rows.length : citation["raw_rows"])

  series[id] = {
    id: id,
    platform: d["platform"],
    launch_month: d["launch_month"],
    months: months,
    counts: counts,
    unique_titles: rows.length,
    raw_rows: raw_rows,
    duration_months: max_idx + 1,
    manufacturer: d["manufacturer"],
    label: d["label"]
  }
  order << id
end

source_json = {}
citations.each do |id, r|
  source_json[id] = {
    author: r["author"], title: r["title"], url: r["url"],
    container: r["container"], accessed: r["accessed"], note: r["note"]
  }
end

db = {
  order: order,
  series: series,
  sources: source_json,
  meta: {
    platform_count: series_defs.map { |d| d["source_id"] }.uniq.length,
    unique_titles: releases.values.sum(&:length),
    snapshot: meta.fetch("snapshot"),
    series_count: series_defs.length
  }
}

json = JSON.generate(db)
out = File.join(ROOT, "data.js")
File.write(out, "// Generated by scripts/build_viewer_data.rb. Do not edit by hand.\nwindow.GAME_RELEASE_DB = #{json};\n", encoding: "UTF-8")
puts "wrote #{out} (#{File.size(out)} bytes)"
puts "#{db[:meta][:unique_titles]} releases / #{db[:meta][:platform_count]} platforms / #{db[:meta][:series_count]} series"
